### ISSUE TITLE
GOAL: Automate AAA ingestion and calculation

### ISSUE THREAD

**Issue by Ivan-TRUF** [truflation/truflation#46]
We need to scrape the AAA data daily and calculate AAA gasoilne and AAA Other fuels based on the following specs - https://docs.google.com/document/d/1kvTzZEHKAFb9dSb5J55NVzTsLjrWchfVdkYS7CFfNYA/edit

**Comment by markholdex** [comment]
Duplicate of: https://github.com/truflation/truflation-ingestors/issues/14
