### ISSUE TITLE
Docs: Overlay collaboration and oracle feed usage

### ISSUE THREAD

**Issue by georgeciubotaru** [truflation/truflation#61]
# [Specs](https://docs.google.com/document/d/1ZItAJ2aVbIfYgLKKpG4cUa0oEgw_RDKmGGHh63t9s4Q/edit)

**Comment by zolotokrylin** [comment]
rename into Goal

**Comment by georgeciubotaru** [comment]
@zolotokrylin Basically, Joseph was assigned to this task to document the existing functionality used for the Overlay connection.

Even though I've requested that, still didn't get any docs on that.
